name: Build Workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
    schedule:
        - cron: "0 8 * * 1"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        env:
            RETENTION_DAYS: "1"
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
            - name: Set retention time for main
              if: github.ref == 'refs/heads/main'
              run: echo "::set-env name=RETENTION_DAYS::7"
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist
                  retention-days: $RETENTION_DAYS
            - name: Static Analysis
              if: github.event_name == 'pull_request'
              run: |
                  pnpm lint
                  pnpm type-check

    deploy-QA:
        needs: build
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        env:
            AZURE_TOKEN_QA_MR: ${{ secrets.AZURE_TOKEN_QA_MR }}
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
            - name: Display structure of downloaded files
              run: ls ./dist
            - name: Install SWA CLI
              run: pnpm install -g @azure/static-web-apps-cli
            - name: Deploy to QA
              run: swa deploy -n stapp-vue-prod ./dist -d $AZURE_TOKEN_QA_MR

    deploy-PROD:
        needs: build
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        env:
            AZURE_TOKEN_PROD_MR: ${{ secrets.AZURE_TOKEN_PROD_MR }}
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
            - name: Display structure of downloaded files
              run: ls ./dist
            - name: Install SWA CLI
              run: pnpm install -g @azure/static-web-apps-cli
            - name: Deploy to PROD
              run: swa deploy -n stapp-vue-prod ./dist -d $AZURE_TOKEN_PROD_MR
